# Generated by Django 5.2.14 on 2026-05-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_log', '0001_initial'),
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('file_path', models.CharField(max_length=260, verbose_name='Путь до сохранённого файла')),
                ('file_name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Исходное имя файла')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активная'), ('archived', 'Архивная')], default='draft', max_length=50, verbose_name='Статус версии')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='document.document', verbose_name='Документ')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit_log.auditlog', verbose_name='Пользователь, загрузивший версию')),
            ],
            options={
                'verbose_name': 'Версия документа',
                'verbose_name_plural': 'Версии документов',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
