# Generated by Django 5.2.14 on 2026-05-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=150, null=True, verbose_name='Администратор')),
                ('external_system', models.CharField(blank=True, max_length=200, null=True, verbose_name='Внешняя система')),
                ('action', models.CharField(choices=[('file_downloaded', 'Скачивание файла документа'), ('access_granted', 'Выдача доступа к документу'), ('access_revoked', 'Отзыв доступа')], default='file_downloaded', max_length=50, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время действия')),
                ('metadata', models.CharField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-created_at'],
            },
        ),
    ]
