# Generated by Django 5.2.14 on 2026-05-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_log', '0001_initial'),
        ('document_version', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='document_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_version.documentversion', verbose_name='Версия документа'),
        ),
    ]
