### ============================================
### Опубликовать версию
### Назначение: опубликовать черновик версии
### Доступ: только администратор
###
### Правило: публиковать можно только версии в статусе "draft"
###
### Побочный эффект:
###   - текущая активная версия становится "archived"
###   - выбранная версия становится "active"
###   - создаётся запись в истории статусов
### ============================================

@baseUrl = http://127.0.0.1:8000
@versionId = 1
@adminBasicAuth = YWRtaW46YWRtaW4xMjM=

POST {{baseUrl}}/api/versions/{{versionId}}/publish/
Authorization: Basic {{adminBasicAuth}}
Accept: application/json