# Generated by Django 5.2.14 on 2026-05-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('external_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_systems', to='document.document', verbose_name='Документ')),
                ('external_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessible_documents', to='external_system.externalsystem', verbose_name='Внешняя система')),
            ],
            options={
                'verbose_name': 'Доступ документа',
                'verbose_name_plural': 'Доступы документов',
                'ordering': ['-created_at'],
            },
        ),
    ]
