# Generated by Django 5.2.14 on 2026-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, verbose_name='Название внешней системы')),
                ('api_key', models.CharField(max_length=255, unique=True, verbose_name='Ключ доступа к API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Внешняя система',
                'verbose_name_plural': 'Внешние системы',
                'ordering': ['-created_at'],
            },
        ),
    ]
