# Generated by Django 5.2.14 on 2026-05-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsystem',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Ключ доступа к API'),
        ),
    ]
