# Generated by Django 5.2.14 on 2026-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=160, verbose_name='Название документа')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('document_type', models.CharField(choices=[('regulation', 'Регламент'), ('methodological_recommendations', 'Методические рекомендации')], db_index=True, default='regulation', max_length=50, verbose_name='Тип документа')),
                ('is_common', models.BooleanField(default=True, verbose_name='Общий документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
