# Generated by Django 5.2.14 on 2026-05-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_log', '0002_initial'),
        ('document_version', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=50, verbose_name='Предыдущий статус версии')),
                ('new_status', models.CharField(max_length=50, verbose_name='Новый статус версии')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit_log.auditlog', verbose_name='Пользователь, изменивший статус')),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='document_version.documentversion', verbose_name='Версия документа')),
            ],
            options={
                'verbose_name': 'История изменения статуса',
                'verbose_name_plural': 'Истории изменения статусов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
